#!/usr/bin/env python3
"""Emit firmware/inc/canned_features.h — one host-computed int8 feature tensor
plus the token ids host ONNX Runtime produces from it.

Gate 4 feeds this straight to the NPU and compares the device's argmax against
kExpectedTokens. It removes the microphone, the MDF decimator, the log-mel front
end and the gain stage from the comparison, so a mismatch can only be the model,
the runtime, or cache coherency.

    python firmware/tools/gen_canned_features.py [utterance_key]

Run from the repo root with the zoo venv active.
"""
import json, sys, importlib.util
import numpy as np, soundfile as sf, onnxruntime as ort

REPO = "."
SCALE = 0.120522417128086          # compile/reports/g800_st_autosched/io_contract.h
T, NMEL, NVOCAB, BLANK = 800, 80, 1025, 1024
LEAD_IN = 4800                     # samples of silence before speech, as eval/ does

# fe.py carries a hardcoded scratchpad path for the vocab; load it with that patched
src = open(f"{REPO}/model/fe.py").read()
src = src.replace(
    "/tmp/claude-1000/-home-claroche-stm32n6-tts/f2087db5-f2ba-4413-ba1b-2f3dbcb6780e/scratchpad/citrinet/vocab.txt",
    f"{REPO}/tokenizer/vocab.txt")
fe = type(sys)("fe"); fe.__file__ = f"{REPO}/model/fe.py"
exec(compile(src, "fe.py", "exec"), fe.__dict__)

key = sys.argv[1] if len(sys.argv) > 1 else "1272-128104-0000"
recs = json.load(open(f"{REPO}/eval/results/recs.json"))
rec = next(r for r in recs if r["k"] == key)
path = rec["f"].replace(
    "/tmp/claude-1000/-home-claroche-stm32n6-tts/f2087db5-f2ba-4413-ba1b-2f3dbcb6780e/scratchpad/adv/",
    f"{REPO}/corpus/")

wav, sr = sf.read(path)
assert sr == 16000, sr
wav = wav.astype(np.float32)

nwin = (T - 1) * 160 + 1
buf = np.zeros(nwin, dtype=np.float32)
n = min(len(wav), nwin - LEAD_IN)
buf[LEAD_IN:LEAD_IN + n] = wav[:n]

mel = fe.norm_pf(fe.nemo_mel(buf))                       # (80, 800) float32
assert mel.shape == (NMEL, T), mel.shape
q = np.clip(np.round(mel / SCALE), -128, 127).astype(np.int8)

# Host reference: feed the DEQUANTISED int8 so host and device see identical values.
sess = ort.InferenceSession(f"{REPO}/artifacts/onnx/q800_real.onnx",
                            providers=["CPUExecutionProvider"])
logits = sess.run(None, {sess.get_inputs()[0].name:
                         (q.astype(np.float32) * SCALE)[None]})[0]
ids = logits.reshape(-1, NVOCAB).argmax(-1).astype(np.int32)

vocab = [l.rsplit(" ", 1)[0] for l in
         open(f"{REPO}/tokenizer/vocab.txt").read().split("\n") if l.strip()]
collapsed, prev = [], -1
for i in ids:
    if i != prev and i != BLANK: collapsed.append(int(i))
    prev = i
text = "".join(vocab[t] for t in collapsed).replace("▁", " ").strip()

flat = q.ravel()                                          # mel-major == CHANNEL_FIRST {80,800,1}
assert flat.size == NMEL * T == 64000

out = [f'''/* GENERATED by firmware/tools/gen_canned_features.py -- do not edit.
 *
 * utterance : {key}  ({rec["d"]:.3f} s)
 * reference : {rec["ref"]}
 * host int8 : {text}
 *
 * Layout is mel-major, matching the model input {{80, 800, 1}} CHANNEL_FIRST.
 * Quantised with the compiled scale {SCALE}; read the scale from
 * info.inputs[0].scale.data[0] at runtime and assert it matches.
 */
#ifndef CANNED_FEATURES_H
#define CANNED_FEATURES_H
#include <stdint.h>

#define CANNED_NMEL      {NMEL}
#define CANNED_T         {T}
#define CANNED_NVOCAB    {NVOCAB}
#define CANNED_BLANK     {BLANK}
#define CANNED_SCALE     {SCALE}f
#define CANNED_N_FRAMES  {len(ids)}

static const int8_t kCannedFeatures[{flat.size}] = {{''']

for i in range(0, flat.size, 24):
    out.append("  " + ",".join(f"{v:4d}" for v in flat[i:i + 24]) + ",")
out.append("};\n")
out.append(f"/* argmax per frame from host ONNX Runtime on exactly these bytes */")
out.append(f"static const uint16_t kExpectedTokens[{len(ids)}] = {{")
for i in range(0, len(ids), 20):
    out.append("  " + ",".join(f"{v:4d}" for v in ids[i:i + 20]) + ",")
out.append("};\n")
out.append("#endif /* CANNED_FEATURES_H */")

open(f"{REPO}/firmware/inc/canned_features.h", "w").write("\n".join(out))
print(f"utterance : {key}")
print(f"reference : {rec['ref']}")
print(f"host int8 : {text}")
print(f"int8 range: {int(q.min())} .. {int(q.max())}")
print(f"wrote firmware/inc/canned_features.h  ({flat.size} B tensor, {len(ids)} frames)")
