#!/usr/bin/env python3
"""Emit firmware/inc/citrinet_fe_tables.h — the two constant tables the C log-mel
front end needs: a *symmetric* Hann window and the Slaney mel filterbank in
run-length (sparse) form.

    python firmware/tools/gen_mel_tables.py            # write the header
    python firmware/tools/gen_mel_tables.py --check    # regenerate, diff, exit 1 on drift

Why this exists rather than ST's GenHeader/lookup_tables_generator.py:

  * ST's generator drags in hydra-core, omegaconf, munch and seaborn to write two
    C files, and hardcodes SILENCE_THR 3000.0F.
  * It builds the window with librosa.filters.get_window('hann', 400), which is
    the *periodic* Hann.  NeMo uses torch.hann_window(400, periodic=False), i.e.
    scipy.signal.get_window("hann", 400, fftbins=False).  The two differ in every
    sample by up to 1/400 of the amplitude.
  * Its YAML has no validated norm=slaney + htk=False + power=2.0 + 80-mel path.

Every literal is printed with %.9g of the float32 value.  FLT_DECIMAL_DIG is 9,
so the C compiler parses each one back to the identical float32 — the C tables
are bit-for-bit the float32 arrays model/fe.py uses.

Authority for the parameters: model/fe.py (which is also the parity oracle) and
model/fe_reference.py.
"""
import argparse
import os
import sys

import numpy as np
import librosa
import scipy.signal

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, "firmware", "inc", "citrinet_fe_tables.h")

# --- the spec, copied from model/fe.py --------------------------------------
SR = 16000
N_FFT = 512
WIN = 400
HOP = 160
N_MELS = 80
FMIN, FMAX = 0, SR / 2
MEL_NORM = "slaney"


def f32(x):
    """Round-trip-exact C float literal for a value, taken through float32."""
    v = float(np.float32(x))
    if v == 0.0:
        return "0.0f"  # keeps -0.0 out of the tables; the window's ends are +0
    return "%.9gf" % v


def fnv1a(buf):
    h = 0x811C9DC5
    for b in buf:
        h = ((h ^ b) * 0x01000193) & 0xFFFFFFFF
    return h


def rows(vals, per_line, indent="  "):
    out = []
    for i in range(0, len(vals), per_line):
        out.append(indent + " ".join(vals[i:i + per_line]))
    return out


def build():
    # symmetric Hann == torch.hann_window(400, periodic=False)
    win = scipy.signal.get_window("hann", WIN, fftbins=False)
    win32 = win.astype(np.float32)
    assert win32.shape == (WIN,)
    assert np.abs(win32 - win32[::-1]).max() == 0.0, "window is not symmetric"

    fb = librosa.filters.mel(sr=SR, n_fft=N_FFT, n_mels=N_MELS,
                             fmin=FMIN, fmax=FMAX, norm=MEL_NORM).astype(np.float32)
    assert fb.shape == (N_MELS, N_FFT // 2 + 1)

    starts, lens, weights = [], [], []
    for m in range(N_MELS):
        nz = np.nonzero(fb[m])[0]
        assert nz.size > 0, f"mel row {m} is all zero — filterbank is degenerate"
        s, e = int(nz[0]), int(nz[-1])
        assert e - s + 1 == nz.size, f"mel row {m} is not one contiguous run"
        starts.append(s)
        lens.append(nz.size)
        weights.extend(fb[m, s:e + 1].tolist())

    weights = np.asarray(weights, dtype=np.float32)
    assert weights.size == int((fb != 0).sum())
    assert max(lens) <= 255, "run length no longer fits uint8_t"
    max_bin = max(s + l - 1 for s, l in zip(starts, lens))

    h = fnv1a(win32.tobytes() + weights.tobytes()
              + np.asarray(starts, np.uint16).tobytes()
              + np.asarray(lens, np.uint8).tobytes())

    nnz = int(weights.size)
    dense_b = fb.size * 4
    sparse_b = nnz * 4 + N_MELS * 2 + N_MELS * 1
    hann_b = WIN * 4

    txt = []
    A = txt.append
    A("/* GENERATED by firmware/tools/gen_mel_tables.py -- do not edit.")
    A(" *")
    A(" * sr=%d  n_fft=%d  win_length=%d  hop=%d  n_mels=%d  fmin=%g  fmax=%g"
      % (SR, N_FFT, WIN, HOP, N_MELS, FMIN, FMAX))
    A(" * window : scipy.signal.get_window(\"hann\", %d, fftbins=False)   <- SYMMETRIC" % WIN)
    A(" * mel    : librosa.filters.mel(norm=\"%s\", htk=False), float32" % MEL_NORM)
    A(" *")
    A(" * The filterbank is %.3f%% non-zero (%d of %d), every row one contiguous"
      % (100.0 * nnz / fb.size, nnz, fb.size))
    A(" * run of %d..%d bins, highest bin touched %d (so the Nyquist bin is never"
      % (min(lens), max(lens), max_bin))
    A(" * read and CMSIS's 256-bin filterbank generator bug is moot here).")
    A(" *")
    A(" *   dense  float32 [%d][%d]           %7d B" % (N_MELS, N_FFT // 2 + 1, dense_b))
    A(" *   sparse w[%d] + start[%d] + len[%d]  %7d B   (%.1fx smaller)"
      % (nnz, N_MELS, N_MELS, sparse_b, dense_b / sparse_b))
    A(" *   hann   float32 [%d]                %7d B" % (WIN, hann_b))
    A(" *   TOTAL                              %7d B of .rodata" % (sparse_b + hann_b))
    A(" *")
    A(" * Cost per frame is %d multiply-accumulates instead of %d for a dense"
      % (nnz, fb.size))
    A(" * 80x%d matmul: %.1fx fewer." % (N_FFT // 2 + 1, fb.size / nnz))
    A(" */")
    A("#ifndef CITRINET_FE_TABLES_H")
    A("#define CITRINET_FE_TABLES_H")
    A("")
    A("#include <stdint.h>")
    A("")
    A("#define CITRINET_FE_TAB_SR      %d" % SR)
    A("#define CITRINET_FE_TAB_NFFT    %d" % N_FFT)
    A("#define CITRINET_FE_TAB_WIN     %d" % WIN)
    A("#define CITRINET_FE_TAB_HOP     %d" % HOP)
    A("#define CITRINET_FE_TAB_NMEL    %d" % N_MELS)
    A("#define CITRINET_FE_TAB_NNZ     %d" % nnz)
    A("#define CITRINET_FE_TAB_MAXBIN  %d" % max_bin)
    A("/* FNV-1a over hann|weights|start|len, for provenance checks */")
    A("#define CITRINET_FE_TAB_FNV1A   0x%08xu" % h)
    A("")
    A("/* symmetric Hann, applied at offset (NFFT-WIN)/2 = %d inside the %d-point frame */"
      % ((N_FFT - WIN) // 2, N_FFT))
    A("static const float kCitrinetHann[%d] = {" % WIN)
    txt.extend(rows([f32(v) + "," for v in win32], 6))
    A("};")
    A("")
    A("/* concatenated non-zero weights, mel bin 0 first */")
    A("static const float kCitrinetMelW[%d] = {" % nnz)
    txt.extend(rows([f32(v) + "," for v in weights], 6))
    A("};")
    A("")
    A("/* first FFT bin of each mel row */")
    A("static const uint16_t kCitrinetMelStart[%d] = {" % N_MELS)
    txt.extend(rows(["%d," % v for v in starts], 16))
    A("};")
    A("")
    A("/* run length of each mel row; offset into kCitrinetMelW is the running sum */")
    A("static const uint8_t kCitrinetMelLen[%d] = {" % N_MELS)
    txt.extend(rows(["%d," % v for v in lens], 16))
    A("};")
    A("")
    A("#endif /* CITRINET_FE_TABLES_H */")
    A("")

    stats = dict(nnz=nnz, dense_b=dense_b, sparse_b=sparse_b, hann_b=hann_b,
                 max_bin=max_bin, minrun=min(lens), maxrun=max(lens), fnv=h,
                 pct=100.0 * nnz / fb.size)
    return "\n".join(txt), stats


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="regenerate and compare against the file on disk")
    args = ap.parse_args()

    text, s = build()
    if args.check:
        have = open(OUT).read() if os.path.exists(OUT) else ""
        if have != text:
            print("DRIFT: %s does not match a fresh generation" % OUT, file=sys.stderr)
            return 1
        print("OK: %s matches a fresh generation (fnv1a 0x%08x)" % (OUT, s["fnv"]))
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write(text)
    print("wrote %s" % OUT)
    print("  non-zero mel weights : %d of %d  (%.3f %%), runs %d..%d, max bin %d"
          % (s["nnz"], 80 * 257, s["pct"], s["minrun"], s["maxrun"], s["max_bin"]))
    print("  filterbank .rodata   : %d B sparse vs %d B dense  (%.1fx)"
          % (s["sparse_b"], s["dense_b"], s["dense_b"] / s["sparse_b"]))
    print("  hann window .rodata  : %d B" % s["hann_b"])
    print("  total .rodata        : %d B" % (s["sparse_b"] + s["hann_b"]))
    print("  MAC/frame            : %d vs %d dense  (%.1fx)"
          % (s["nnz"], 80 * 257, 80 * 257 / s["nnz"]))
    print("  fnv1a                : 0x%08x" % s["fnv"])
    return 0


if __name__ == "__main__":
    sys.exit(main())
