#!/bin/bash
# Reapply every change this project makes to the vendored ST audio package.
#
# vendor/ is a pristine `git clone` and is gitignored, so this script is the
# authoritative record of what we changed and why. Idempotent.
#
#   bash firmware/apply_vendor_mods.sh
set -euo pipefail

R="$(cd "$(dirname "$0")/.." && pwd)"
V="$R/vendor/STM32N6-GettingStarted-Audio"
STT_QUIET=1 . "$(cd "$(dirname "$0")/.." && pwd)/env.sh"
STEDGEAI=$STEDGEAI_ROOT
[ -d "$V" ] || { echo "clone STM32N6-GettingStarted-Audio into vendor/ first"; exit 1; }

say() { printf '  %s\n' "$*"; }

# ---------------------------------------------------------------- 1. runtime
# Our model is generated by ST Edge AI Core 4.0.1, whose ll_aton is 1.1.3-275.
# The package ships 1.1.3-262 and network.c has a hard #error on the mismatch.
echo "[1] AI middleware -> ST Edge AI 4.0.1 (ll_aton 275, NetworkRuntime1201)"
A="$V/Middlewares/ST/AI"; B="$STEDGEAI/Middlewares/ST/AI"
if grep -q "(262)" "$A/Npu/ll_aton/ll_aton_version.h" 2>/dev/null; then
  [ -d "$A.v262bak" ] || cp -r "$A" "$A.v262bak"
  for d in Inc Lib Misc Npu Reloc SystemPerformance; do
    rm -rf "$A/$d"; cp -r "$B/$d" "$A/$d"
  done
  say "replaced; version now $(grep -o '(2[0-9][0-9])' "$A/Npu/ll_aton/ll_aton_version.h" | head -1)"
else say "already 275"; fi
sed -i 's/NetworkRuntime1200/NetworkRuntime1201/g' "$V/Projects/GS/Makefile"

# ---------------------------------------------------------------- 2. ai_dpu
# The stock output check demands float32 OR rank 2. Citrinet's CTC head is int8
# rank 3, so it hits Error_Handler() -> __disable_irq(); while(1): a silent hang.
echo "[2] ai_dpu.c — accept int8 outputs"
python3 - "$V" <<'PY'
import sys
p=f"{sys.argv[1]}/Projects/Dpu/ai_dpu.c"; s=open(p).read()
if 'STAI_FORMAT_S8      != pxInfo->outputs' in s: print("  already patched"); raise SystemExit
old='''    if (STAI_FORMAT_FLOAT32 != pxInfo->outputs[i].format &&\\
        2 != pxInfo->outputs[i].shape.size)'''
new='''    /* stm32n6-stt: Citrinet's CTC head is STAI_FORMAT_S8 at rank 3 ({100,1025,1}),
     * so both conjuncts hold and the model is rejected into a silent hang. */
    if (STAI_FORMAT_FLOAT32 != pxInfo->outputs[i].format &&\\
        STAI_FORMAT_S8      != pxInfo->outputs[i].format &&\\
        2 != pxInfo->outputs[i].shape.size)'''
assert old in s, "ai_dpu output check not found"
open(p,'w').write(s.replace(old,new)); print("  patched")
PY

# ---------------------------------------------------------------- 3. cpu_stats
# GCC 14 makes implicit-function-declaration an error; assert.h used to arrive
# transitively through the pre-4.0 AI headers.
echo "[3] cpu_stats.c — explicit assert.h"
python3 - "$V" <<'PY'
import sys
p=f"{sys.argv[1]}/Projects/Common/cpu_stats.c"; s=open(p).read()
if '#include <assert.h>' in s: print("  already patched"); raise SystemExit
i=s.index('#include')
open(p,'w').write(s[:i]+'#include <assert.h>   /* stm32n6-stt: was transitive via the pre-4.0 AI middleware */\n'+s[i:])
print("  patched")
PY

# ---------------------------------------------------------------- 4. Makefile
# `OPT += ...` inside the Makefile is silently DISCARDED when OPT is set on the
# command line, which drops -flax-vector-conversions and breaks CMSIS-DSP. Add a
# proper extension point instead.
echo "[4] Makefile — EXTRA_CFLAGS extension point"
python3 - "$V" <<'PY'
import sys
p=f"{sys.argv[1]}/Projects/GS/Makefile"; s=open(p).read()
if 'EXTRA_CFLAGS' in s: print("  already patched"); raise SystemExit
a='OPT  += -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"'
assert a in s
open(p,'w').write(s.replace(a, a+'\n# stm32n6-stt: never override OPT on the command line -- make discards every\n# "OPT +=" above for command-line variables, including -flax-vector-conversions.\nOPT  += $(EXTRA_CFLAGS)',1))
print("  patched")
PY

# ---------------------------------------------------------------- 5. linker
# The Gate-4 canned tensor is 64,000 B of .rodata and RAM is the only region.
# The heap this reserves is for the capture ring buffer, which the canned path
# never allocates. Revisit at Gate 5, which restructures the capture path anyway.
echo "[5] linker — heap 64K -> 32K"
sed -i 's|^_Min_Heap_Size = 0x10000;.*|_Min_Heap_Size = 0x8000; /* stm32n6-stt: see firmware/apply_vendor_mods.sh */|' \
    "$V/Projects/GS/STM32CubeIDE/STM32N657XX_LRUN.ld"
grep -q "0x8000" "$V/Projects/GS/STM32CubeIDE/STM32N657XX_LRUN.ld" && say "ok"

# ---------------------------------------------------------------- 6. model
echo "[6] model — install Citrinet over the built-in AED"
M="$V/Projects/X-CUBE-AI/models"
G="$R/artifacts/model_c"
# The graph MUST be the post-fold, post-relu4d one. artifacts/model_c/ once held
# the pre-fold build, which compiles cleanly, reports 0 software epochs, and
# stalls the NPU forever (board/GATE4.md rounds 10-19). Check before installing,
# rather than discovering it as a board that boots and then never answers.
WANT_NET_MD5=d8806930c51a4a34aa02f78e2a0a0668
WANT_W_MD5=c81d84a7a9cbff549bfa9fa4df8923ff
if [ -f "$G/network.c" ]; then
  got_net=$(md5sum < "$G/network.c" | cut -d' ' -f1)
  got_w=$(md5sum < "$G/network_atonbuf.xSPI2.raw" | cut -d' ' -f1)
  if [ "$got_net" != "$WANT_NET_MD5" ] || [ "$got_w" != "$WANT_W_MD5" ]; then
    say "REFUSING: artifacts/model_c is not the deployed graph."
    say "  network.c md5 $got_net, want $WANT_NET_MD5"
    say "  weights   md5 $got_w, want $WANT_W_MD5"
    say "  rebuild with: compile/gen_model.sh artifacts/onnx/q800_relu4d_all.onnx deploy --install"
    say "  see artifacts/model_c/MANIFEST.txt"
    exit 1
  fi
  for f in network.c network.h stai_network.c stai_network.h; do
    [ -f "$M/$f.aedbak" ] || cp "$M/$f" "$M/$f.aedbak"
    cp "$G/$f" "$M/$f"
  done
  cp "$G/network_atonbuf.xSPI2.raw" "$M/network_data.bin"
  say "installed ($(stat -c%s "$M/network_data.bin") B of weights, md5 verified)"
else
  say "artifacts/model_c missing -- run:"
  say "  compile/gen_model.sh artifacts/onnx/q800_relu4d_all.onnx deploy --install"
fi

echo
echo "Done. Build with:"
echo "  make bm -j8 GCC_PATH=$ARM_BIN \\"
echo "       EXTRA_CFLAGS=\"-DGATE4_CANNED -I$R/firmware/inc\""
echo "NOTE: the Gate 4 instrumentation (audio_bm.c/.h, app_config.h,"
echo "      stm32n6xx_it.c) is applied separately:"
echo "        git -C vendor/STM32N6-GettingStarted-Audio apply \\"
echo "            $R/firmware/vendor-mods/gate4.patch"
echo "      See board/BUILD.md sections 1-2. The older"
echo "      firmware/vendor-mods/gate4.patch is the application: capture path,"
echo "      front end call, CTC decode, LCD, push-to-talk and instrumentation."
echo "      It reverse-applies cleanly, so git apply -R undoes it."
